// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

const TableNameBooksLesson = "books__lessons"

// BooksLesson mapped from table <books__lessons>
type BooksLesson struct {
	ID       int32  `gorm:"column:id;type:integer;not null" json:"id"`
	BookID   *int32 `gorm:"column:book_id;type:integer" json:"book_id"`
	LessonID *int32 `gorm:"column:lesson_id;type:integer" json:"lesson_id"`
}

// TableName BooksLesson's table name
func (*BooksLesson) TableName() string {
	return TableNameBooksLesson
}
