// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

const TableNameComponentsEditorGrammer = "components_editor_grammers"

// ComponentsEditorGrammer mapped from table <components_editor_grammers>
type ComponentsEditorGrammer struct {
	ID      int32   `gorm:"column:id;type:integer;not null" json:"id"`
	Content *string `gorm:"column:content;type:text" json:"content"`
}

// TableName ComponentsEditorGrammer's table name
func (*ComponentsEditorGrammer) TableName() string {
	return TableNameComponentsEditorGrammer
}
