// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

const TableNameCoreStore = "core_store"

// CoreStore mapped from table <core_store>
type CoreStore struct {
	ID          int32   `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	Key         *string `gorm:"column:key;type:character varying(255)" json:"key"`
	Value       *string `gorm:"column:value;type:text" json:"value"`
	Type        *string `gorm:"column:type;type:character varying(255)" json:"type"`
	Environment *string `gorm:"column:environment;type:character varying(255)" json:"environment"`
	Tag         *string `gorm:"column:tag;type:character varying(255)" json:"tag"`
}

// TableName CoreStore's table name
func (*CoreStore) TableName() string {
	return TableNameCoreStore
}
