// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

const TableNameDefaultFreeMaterialsAdminMaterial = "default_free_materials__admin_materials"

// DefaultFreeMaterialsAdminMaterial mapped from table <default_free_materials__admin_materials>
type DefaultFreeMaterialsAdminMaterial struct {
	ID                    int32  `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	DefaultFreeMaterialID *int32 `gorm:"column:default_free_material_id;type:integer" json:"default_free_material_id"`
	AdminMaterialID       *int32 `gorm:"column:admin-material_id;type:integer" json:"admin-material_id"`
}

// TableName DefaultFreeMaterialsAdminMaterial's table name
func (*DefaultFreeMaterialsAdminMaterial) TableName() string {
	return TableNameDefaultFreeMaterialsAdminMaterial
}
