// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameEditorTheme = "editor_themes"

// EditorTheme mapped from table <editor_themes>
type EditorTheme struct {
	ID           int32           `gorm:"column:id;type:integer;not null" json:"id"`
	Name         *string         `gorm:"column:name;type:character varying(255)" json:"name"`
	Tag          *string         `gorm:"column:tag;type:character varying(255)" json:"tag"`
	Content      *datatypes.JSON `gorm:"column:content;type:jsonb" json:"content"`
	PublishedAt  *time.Time      `gorm:"column:published_at;type:timestamp with time zone" json:"published_at"`
	CreatedBy    *int32          `gorm:"column:created_by;type:integer" json:"created_by"`
	UpdatedBy    *int32          `gorm:"column:updated_by;type:integer" json:"updated_by"`
	CreatedAt    *time.Time      `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    *time.Time      `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Organization *int32          `gorm:"column:organization;type:integer" json:"organization"`
}

// TableName EditorTheme's table name
func (*EditorTheme) TableName() string {
	return TableNameEditorTheme
}
