// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

const TableNameEditorGrammersCategorie = "editor_grammers__categories"

// EditorGrammersCategorie mapped from table <editor_grammers__categories>
type EditorGrammersCategorie struct {
	ID                      int32  `gorm:"column:id;type:integer;not null" json:"id"`
	EditorGrammerID         *int32 `gorm:"column:editor_grammer_id;type:integer" json:"editor_grammer_id"`
	EditorCategoryGrammerID *int32 `gorm:"column:editor-category-grammer_id;type:integer" json:"editor-category-grammer_id"`
}

// TableName EditorGrammersCategorie's table name
func (*EditorGrammersCategorie) TableName() string {
	return TableNameEditorGrammersCategorie
}
