// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

const TableNameEditorAudiosCategorie = "editor_audios__categories"

// EditorAudiosCategorie mapped from table <editor_audios__categories>
type EditorAudiosCategorie struct {
	ID                    int32  `gorm:"column:id;type:integer;not null" json:"id"`
	EditorAudioID         *int32 `gorm:"column:editor_audio_id;type:integer" json:"editor_audio_id"`
	EditorCategoryAudioID *int32 `gorm:"column:editor-category-audio_id;type:integer" json:"editor-category-audio_id"`
}

// TableName EditorAudiosCategorie's table name
func (*EditorAudiosCategorie) TableName() string {
	return TableNameEditorAudiosCategorie
}
