// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

import (
	"time"
)

const TableNameLegalDocument = "legal_documents"

// LegalDocument mapped from table <legal_documents>
type LegalDocument struct {
	ID          int32      `gorm:"column:id;type:integer;not null" json:"id"`
	Name        *string    `gorm:"column:name;type:character varying(255)" json:"name"`
	Version     *string    `gorm:"column:version;type:character varying(255)" json:"version"`
	Content     *string    `gorm:"column:content;type:text" json:"content"`
	Type        *string    `gorm:"column:type;type:character varying(255)" json:"type"`
	PublishedAt *time.Time `gorm:"column:published_at;type:timestamp with time zone" json:"published_at"`
	CreatedBy   *int32     `gorm:"column:created_by;type:integer" json:"created_by"`
	UpdatedBy   *int32     `gorm:"column:updated_by;type:integer" json:"updated_by"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName LegalDocument's table name
func (*LegalDocument) TableName() string {
	return TableNameLegalDocument
}
