// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

const TableNameLessonsGrammer = "lessons__grammers"

// LessonsGrammer mapped from table <lessons__grammers>
type LessonsGrammer struct {
	ID        int32  `gorm:"column:id;type:integer;not null" json:"id"`
	LessonID  *int32 `gorm:"column:lesson_id;type:integer" json:"lesson_id"`
	GrammerID *int32 `gorm:"column:grammer_id;type:integer" json:"grammer_id"`
}

// TableName LessonsGrammer's table name
func (*LessonsGrammer) TableName() string {
	return TableNameLessonsGrammer
}
