// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameMaterialContentSchema = "material_content_schemas"

// MaterialContentSchema mapped from table <material_content_schemas>
type MaterialContentSchema struct {
	ID          int32           `gorm:"column:id;type:integer;not null" json:"id"`
	JSONSchema  *datatypes.JSON `gorm:"column:json_schema;type:jsonb" json:"json_schema"`
	PublishedAt *time.Time      `gorm:"column:published_at;type:timestamp with time zone" json:"published_at"`
	CreatedBy   *int32          `gorm:"column:created_by;type:integer" json:"created_by"`
	UpdatedBy   *int32          `gorm:"column:updated_by;type:integer" json:"updated_by"`
	CreatedAt   *time.Time      `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time      `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName MaterialContentSchema's table name
func (*MaterialContentSchema) TableName() string {
	return TableNameMaterialContentSchema
}
