// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

import (
	"time"
)

const TableNameMaterialDefaultLog = "material_default_logs"

// MaterialDefaultLog mapped from table <material_default_logs>
type MaterialDefaultLog struct {
	ID        int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	UserID    *int32     `gorm:"column:user_id;type:integer" json:"user_id"`
	CreatedBy *int32     `gorm:"column:created_by;type:integer" json:"created_by"`
	UpdatedBy *int32     `gorm:"column:updated_by;type:integer" json:"updated_by"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName MaterialDefaultLog's table name
func (*MaterialDefaultLog) TableName() string {
	return TableNameMaterialDefaultLog
}
