// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameMaterialElement = "material_elements"

// MaterialElement mapped from table <material_elements>
type MaterialElement struct {
	ID          int32           `gorm:"column:id;type:integer;not null" json:"id"`
	Material    *int32          `gorm:"column:material;type:integer" json:"material"`
	Element     *datatypes.JSON `gorm:"column:element;type:jsonb" json:"element"`
	PublishedAt *time.Time      `gorm:"column:published_at;type:timestamp with time zone" json:"published_at"`
	CreatedBy   *int32          `gorm:"column:created_by;type:integer" json:"created_by"`
	UpdatedBy   *int32          `gorm:"column:updated_by;type:integer" json:"updated_by"`
	CreatedAt   *time.Time      `gorm:"column:created_at;type:timestamp with time zone" json:"created_at"`
	UpdatedAt   *time.Time      `gorm:"column:updated_at;type:timestamp with time zone" json:"updated_at"`
}

// TableName MaterialElement's table name
func (*MaterialElement) TableName() string {
	return TableNameMaterialElement
}
