// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

const TableNameStrapiAdministrator = "strapi_administrator"

// StrapiAdministrator mapped from table <strapi_administrator>
type StrapiAdministrator struct {
	ID                 int32   `gorm:"column:id;type:integer;not null" json:"id"`
	Firstname          *string `gorm:"column:firstname;type:character varying(255)" json:"firstname"`
	Lastname           *string `gorm:"column:lastname;type:character varying(255)" json:"lastname"`
	Username           *string `gorm:"column:username;type:character varying(255)" json:"username"`
	Email              string  `gorm:"column:email;type:character varying(255);not null" json:"email"`
	Password           *string `gorm:"column:password;type:character varying(255)" json:"password"`
	ResetPasswordToken *string `gorm:"column:resetPasswordToken;type:character varying(255)" json:"resetPasswordToken"`
	RegistrationToken  *string `gorm:"column:registrationToken;type:character varying(255)" json:"registrationToken"`
	IsActive           *bool   `gorm:"column:isActive;type:boolean" json:"isActive"`
	Blocked            *bool   `gorm:"column:blocked;type:boolean" json:"blocked"`
	PreferedLanguage   *string `gorm:"column:preferedLanguage;type:character varying(255)" json:"preferedLanguage"`
}

// TableName StrapiAdministrator's table name
func (*StrapiAdministrator) TableName() string {
	return TableNameStrapiAdministrator
}
