// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

import (
	"time"
)

const TableNameStrapiRole = "strapi_role"

// StrapiRole mapped from table <strapi_role>
type StrapiRole struct {
	ID          int32      `gorm:"column:id;type:integer;not null" json:"id"`
	Name        string     `gorm:"column:name;type:character varying(255);not null" json:"name"`
	Code        string     `gorm:"column:code;type:character varying(255);not null" json:"code"`
	Description *string    `gorm:"column:description;type:character varying(255)" json:"description"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName StrapiRole's table name
func (*StrapiRole) TableName() string {
	return TableNameStrapiRole
}
