// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameStrapiPermission = "strapi_permission"

// StrapiPermission mapped from table <strapi_permission>
type StrapiPermission struct {
	ID         int32           `gorm:"column:id;type:integer;not null" json:"id"`
	Action     string          `gorm:"column:action;type:character varying(255);not null" json:"action"`
	Subject    *string         `gorm:"column:subject;type:character varying(255)" json:"subject"`
	Properties *datatypes.JSON `gorm:"column:properties;type:jsonb" json:"properties"`
	Conditions *datatypes.JSON `gorm:"column:conditions;type:jsonb" json:"conditions"`
	Role       *int32          `gorm:"column:role;type:integer" json:"role"`
	CreatedAt  *time.Time      `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  *time.Time      `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName StrapiPermission's table name
func (*StrapiPermission) TableName() string {
	return TableNameStrapiPermission
}
