// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

import (
	"time"
)

const TableNameTempHeaderFooter = "temp_header_footers"

// TempHeaderFooter mapped from table <temp_header_footers>
type TempHeaderFooter struct {
	ID          int32      `gorm:"column:id;type:integer;not null" json:"id"`
	PublishedAt *time.Time `gorm:"column:published_at;type:timestamp with time zone" json:"published_at"`
	CreatedBy   *int32     `gorm:"column:created_by;type:integer" json:"created_by"`
	UpdatedBy   *int32     `gorm:"column:updated_by;type:integer" json:"updated_by"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TempHeaderFooter's table name
func (*TempHeaderFooter) TableName() string {
	return TableNameTempHeaderFooter
}
