// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

const TableNameUploadFileMorph = "upload_file_morph"

// UploadFileMorph mapped from table <upload_file_morph>
type UploadFileMorph struct {
	ID           int32   `gorm:"column:id;type:integer;not null" json:"id"`
	UploadFileID *int32  `gorm:"column:upload_file_id;type:integer" json:"upload_file_id"`
	RelatedID    *int32  `gorm:"column:related_id;type:integer" json:"related_id"`
	RelatedType  *string `gorm:"column:related_type;type:text" json:"related_type"`
	Field        *string `gorm:"column:field;type:text" json:"field"`
	Order_       *int32  `gorm:"column:order;type:integer" json:"order"`
}

// TableName UploadFileMorph's table name
func (*UploadFileMorph) TableName() string {
	return TableNameUploadFileMorph
}
