// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package table

const TableNameUsersPermissionsRole = "users-permissions_role"

// UsersPermissionsRole mapped from table <users-permissions_role>
type UsersPermissionsRole struct {
	ID          *int32  `gorm:"column:id;type:integer;not null" json:"id"`
	Name        string  `gorm:"column:name;type:character varying(255);not null" json:"name"`
	Description *string `gorm:"column:description;type:character varying(255)" json:"description"`
	Type        *string `gorm:"column:type;type:character varying(255)" json:"type"`
	CreatedBy   *int32  `gorm:"column:created_by;type:integer" json:"created_by"`
	UpdatedBy   *int32  `gorm:"column:updated_by;type:integer" json:"updated_by"`
}

// TableName UsersPermissionsRole's table name
func (*UsersPermissionsRole) TableName() string {
	return TableNameUsersPermissionsRole
}
