// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"river0825/cleanarchitecture/core/dependency/storage/gorm/table"
)

func newPlan(db *gorm.DB, opts ...gen.DOOption) plan {
	_plan := plan{}

	_plan.planDo.UseDB(db, opts...)
	_plan.planDo.UseModel(&table.Plan{})

	tableName := _plan.planDo.TableName()
	_plan.ALL = field.NewAsterisk(tableName)
	_plan.ID = field.NewInt32(tableName, "id")
	_plan.PlanName = field.NewString(tableName, "plan_name")
	_plan.Description = field.NewString(tableName, "description")
	_plan.CurrentPrice = field.NewInt32(tableName, "current_price")
	_plan.DurationYear = field.NewInt32(tableName, "duration_year")
	_plan.DurationMonth = field.NewInt32(tableName, "duration_month")
	_plan.DurationDay = field.NewInt32(tableName, "duration_day")
	_plan.MaximumMaterials = field.NewInt32(tableName, "maximum_materials")
	_plan.CreatedBy = field.NewInt32(tableName, "created_by")
	_plan.UpdatedBy = field.NewInt32(tableName, "updated_by")
	_plan.CreatedAt = field.NewTime(tableName, "created_at")
	_plan.UpdatedAt = field.NewTime(tableName, "updated_at")
	_plan.FullAccess = field.NewBool(tableName, "full_access")

	_plan.fillFieldMap()

	return _plan
}

type plan struct {
	planDo

	ALL              field.Asterisk
	ID               field.Int32
	PlanName         field.String
	Description      field.String
	CurrentPrice     field.Int32
	DurationYear     field.Int32
	DurationMonth    field.Int32
	DurationDay      field.Int32
	MaximumMaterials field.Int32
	CreatedBy        field.Int32
	UpdatedBy        field.Int32
	CreatedAt        field.Time
	UpdatedAt        field.Time
	FullAccess       field.Bool

	fieldMap map[string]field.Expr
}

func (p plan) Table(newTableName string) *plan {
	p.planDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p plan) As(alias string) *plan {
	p.planDo.DO = *(p.planDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *plan) updateTableName(table string) *plan {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.PlanName = field.NewString(table, "plan_name")
	p.Description = field.NewString(table, "description")
	p.CurrentPrice = field.NewInt32(table, "current_price")
	p.DurationYear = field.NewInt32(table, "duration_year")
	p.DurationMonth = field.NewInt32(table, "duration_month")
	p.DurationDay = field.NewInt32(table, "duration_day")
	p.MaximumMaterials = field.NewInt32(table, "maximum_materials")
	p.CreatedBy = field.NewInt32(table, "created_by")
	p.UpdatedBy = field.NewInt32(table, "updated_by")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.FullAccess = field.NewBool(table, "full_access")

	p.fillFieldMap()

	return p
}

func (p *plan) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *plan) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 13)
	p.fieldMap["id"] = p.ID
	p.fieldMap["plan_name"] = p.PlanName
	p.fieldMap["description"] = p.Description
	p.fieldMap["current_price"] = p.CurrentPrice
	p.fieldMap["duration_year"] = p.DurationYear
	p.fieldMap["duration_month"] = p.DurationMonth
	p.fieldMap["duration_day"] = p.DurationDay
	p.fieldMap["maximum_materials"] = p.MaximumMaterials
	p.fieldMap["created_by"] = p.CreatedBy
	p.fieldMap["updated_by"] = p.UpdatedBy
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["full_access"] = p.FullAccess
}

func (p plan) clone(db *gorm.DB) plan {
	p.planDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p plan) replaceDB(db *gorm.DB) plan {
	p.planDo.ReplaceDB(db)
	return p
}

type planDo struct{ gen.DO }

type IPlanDo interface {
	gen.SubQuery
	Debug() IPlanDo
	WithContext(ctx context.Context) IPlanDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPlanDo
	WriteDB() IPlanDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPlanDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPlanDo
	Not(conds ...gen.Condition) IPlanDo
	Or(conds ...gen.Condition) IPlanDo
	Select(conds ...field.Expr) IPlanDo
	Where(conds ...gen.Condition) IPlanDo
	Order(conds ...field.Expr) IPlanDo
	Distinct(cols ...field.Expr) IPlanDo
	Omit(cols ...field.Expr) IPlanDo
	Join(table schema.Tabler, on ...field.Expr) IPlanDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPlanDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPlanDo
	Group(cols ...field.Expr) IPlanDo
	Having(conds ...gen.Condition) IPlanDo
	Limit(limit int) IPlanDo
	Offset(offset int) IPlanDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPlanDo
	Unscoped() IPlanDo
	Create(values ...*table.Plan) error
	CreateInBatches(values []*table.Plan, batchSize int) error
	Save(values ...*table.Plan) error
	First() (*table.Plan, error)
	Take() (*table.Plan, error)
	Last() (*table.Plan, error)
	Find() ([]*table.Plan, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*table.Plan, err error)
	FindInBatches(result *[]*table.Plan, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*table.Plan) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPlanDo
	Assign(attrs ...field.AssignExpr) IPlanDo
	Joins(fields ...field.RelationField) IPlanDo
	Preload(fields ...field.RelationField) IPlanDo
	FirstOrInit() (*table.Plan, error)
	FirstOrCreate() (*table.Plan, error)
	FindByPage(offset int, limit int) (result []*table.Plan, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPlanDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p planDo) Debug() IPlanDo {
	return p.withDO(p.DO.Debug())
}

func (p planDo) WithContext(ctx context.Context) IPlanDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p planDo) ReadDB() IPlanDo {
	return p.Clauses(dbresolver.Read)
}

func (p planDo) WriteDB() IPlanDo {
	return p.Clauses(dbresolver.Write)
}

func (p planDo) Session(config *gorm.Session) IPlanDo {
	return p.withDO(p.DO.Session(config))
}

func (p planDo) Clauses(conds ...clause.Expression) IPlanDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p planDo) Returning(value interface{}, columns ...string) IPlanDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p planDo) Not(conds ...gen.Condition) IPlanDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p planDo) Or(conds ...gen.Condition) IPlanDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p planDo) Select(conds ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p planDo) Where(conds ...gen.Condition) IPlanDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p planDo) Order(conds ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p planDo) Distinct(cols ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p planDo) Omit(cols ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p planDo) Join(table schema.Tabler, on ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p planDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPlanDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p planDo) RightJoin(table schema.Tabler, on ...field.Expr) IPlanDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p planDo) Group(cols ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p planDo) Having(conds ...gen.Condition) IPlanDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p planDo) Limit(limit int) IPlanDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p planDo) Offset(offset int) IPlanDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p planDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPlanDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p planDo) Unscoped() IPlanDo {
	return p.withDO(p.DO.Unscoped())
}

func (p planDo) Create(values ...*table.Plan) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p planDo) CreateInBatches(values []*table.Plan, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p planDo) Save(values ...*table.Plan) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p planDo) First() (*table.Plan, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*table.Plan), nil
	}
}

func (p planDo) Take() (*table.Plan, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*table.Plan), nil
	}
}

func (p planDo) Last() (*table.Plan, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*table.Plan), nil
	}
}

func (p planDo) Find() ([]*table.Plan, error) {
	result, err := p.DO.Find()
	return result.([]*table.Plan), err
}

func (p planDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*table.Plan, err error) {
	buf := make([]*table.Plan, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p planDo) FindInBatches(result *[]*table.Plan, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p planDo) Attrs(attrs ...field.AssignExpr) IPlanDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p planDo) Assign(attrs ...field.AssignExpr) IPlanDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p planDo) Joins(fields ...field.RelationField) IPlanDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p planDo) Preload(fields ...field.RelationField) IPlanDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p planDo) FirstOrInit() (*table.Plan, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*table.Plan), nil
	}
}

func (p planDo) FirstOrCreate() (*table.Plan, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*table.Plan), nil
	}
}

func (p planDo) FindByPage(offset int, limit int) (result []*table.Plan, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p planDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p planDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p planDo) Delete(models ...*table.Plan) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *planDo) withDO(do gen.Dao) *planDo {
	p.DO = *do.(*gen.DO)
	return p
}
